### Get all contacts
GET https://contact-management-application-node-js.onrender.com/contacts

### Create a new contact
POST https://contact-management-application-node-js.onrender.com/contacts
Content-Type: application/json


{
    "name": "John Doee",
    "email": "johny15234@example.com",
    "phone": "1234567890",
    "address": ""
}
 

### Get a single contact
GET https://contact-management-application-node-js.onrender.com/contacts/1


### Update a contact
PUT https://contact-management-application-node-js.onrender.com/contacts/1
Content-Type: application/json

{
    "name": "Ashik",
    "email": "johny1234@example.com",
    "phone": "9698687766",
    "address": ""
}

 

### Delete a contact
DELETE https://contact-management-application-node-js.onrender.com/contacts/3


